# Generated by Django 4.2 on 2023-10-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_color_name_color_name_color_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cid',
        ),
    ]
