# Generated by Django 4.2 on 2023-10-29 12:12

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_color_image_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='brand.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
