# Generated by Django 4.2 on 2023-11-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_town_city_cartorder_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='shipping',
            new_name='shipping_amount',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='vat',
            new_name='tax_fee',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='shipping',
            new_name='shipping_amount',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='vat',
            new_name='tax_fee',
        ),
    ]
