# Generated by Django 4.2 on 2023-11-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_shipping_cartorder_shipping_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='original_total',
            new_name='initial_total',
        ),
    ]
