# Generated by Django 4.2 on 2023-11-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_original_total_cartorder_initial_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='stripe_payment_intent',
            new_name='stripe_session_id',
        ),
    ]
