# Generated by Django 4.2 on 2023-11-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_stripe_payment_intent_cartorder_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='make_public',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='redemption',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
    ]
