# Generated by Django 4.2 on 2024-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_deliverycouriers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycouriers',
            name='url_parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
