# Generated by Django 4.2 on 2023-10-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='ConfigSettings',
        ),
    ]
